// Result-specific link previews for shared ?style= URLs on `/`.
// Pure helpers — everything here is unit-testable in Node without the
// Workers runtime; functions/_middleware.js owns the HTMLRewriter wiring.
// STYLE_OG is generated by scripts/dump-style-registry.js from the real
// renderer, never hand-edited.
import { STYLE_OG } from "./_og-style-data.js";

// Same normalization script.js applies to the ?style= param on the
// recipient side — a handful of registry slugs use underscores.
export function normalizeStyleParam(raw) {
  if (!raw) return null;
  const key = String(raw).toLowerCase().replace(/_/g, "-").slice(0, 64);
  return Object.prototype.hasOwnProperty.call(STYLE_OG, key) ? key : null;
}

// Render q through the style's per-character map (map/redact styles only —
// the dump omits maps for order-changing or random styles on purpose).
export function styledText(q, map) {
  if (!q || !map) return null;
  let out = "";
  for (const ch of q) out += map[ch] || ch;
  return out;
}

// The preview meta for a shared link, or null when ?style= is absent/unknown
// (the static homepage tags then stand untouched).
export function previewMeta(styleParam, qParam, origin) {
  const key = normalizeStyleParam(styleParam);
  if (!key) return null;
  const entry = STYLE_OG[key];

  // The shared text, bounded and stripped of control chars — it lands in
  // meta attribute values (HTMLRewriter escapes attributes; this just keeps
  // the preview sane).
  const q = qParam
    ? String(qParam).replace(/[\u0000-\u001f\u007f]/g, " ").trim().slice(0, 100)
    : "";

  const styled = styledText(q, entry.map);
  const title = styled
    ? styled + " — UltraTextGen"
    : (q ? q + " in " + entry.name + " — UltraTextGen" : entry.name + " — UltraTextGen");

  return {
    image: origin + entry.img,
    title,
    description: "Someone styled this with UltraTextGen — tap to write your own text in " + entry.name + ", free, no signup.",
  };
}
