#!/usr/bin/env node
'use strict';
/**
 * content-significance.test.js — run: node scripts/lib/content-significance.test.js
 * (npm run test:content-significance). Zero dependencies, no runner, the same
 * idiom as js/counter/counterRules.test.js.
 *
 * This surface decides whether a page's <lastmod> advances, and this repo has
 * mass-bumped the site twice by getting it wrong: 2,533 pages on 2026-08-15/16
 * (aria-labels, three template strings) and, on 2026-08-20, a next run that
 * would have advanced all 4,576 URLs because the static footer landed on
 * every page. Every NON-catch below encodes one of those; every catch keeps
 * the hash honest in the other direction.
 */
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { significanceHash, normalizeText, stripStaticFooter, pickSignificantDate } = require('./content-significance');

let pass = 0, fail = 0;
function t(name, fn) {
  try { fn(); pass++; console.log(`  ok   ${name}`); }
  catch (e) { fail++; console.log(`  FAIL ${name}\n         ${e.message.split('\n')[0]}`); }
}

const FOOTER = (links) => `<!-- BEGIN static footer — generated by scripts/build-static-footer.js from footer.js. Do not edit by hand — run \`npm run build:static-footer\`. -->
<footer class="footer"><div class="footer-inner">${links}</div></footer>
<!-- END static footer -->`;

function page({ title = 'Euro Sign (€): Copy and Paste', desc = 'The euro sign, ready to copy.', h1 = 'Euro Sign',
  body = '<p>The euro sign — copy it below. It works on Discord.</p>', tile = '€', links = '<a href="/library/currency-symbols/">Currency</a>',
  footer = FOOTER('<a href="/guide/">Guides</a><a href="/library/">Library</a>') } = {}) {
  return `<!DOCTYPE html><html lang="en"><head><title>${title}</title><meta name="description" content="${desc}"></head>
<body><div id="shared-header"></div><h1>${h1}</h1>${body}
<button class="symbol-tile" data-symbol="${tile}" aria-label="Copy ${tile}">${tile}</button>
<nav>${links}</nav>${footer}</body></html>`;
}
const H = (o) => significanceHash(page(o));
const base = H();

// ── NON-catches: what must NOT advance lastmod ──────────────────────────────
t('NON-CATCH: a changed static footer (new link, new text) leaves the hash alone', () => {
  assert.strictEqual(H({ footer: FOOTER('<a href="/guide/">Guides</a><a href="/library/">Library</a><a href="/updates/">What changed — this week</a>') }), base);
});
t('NON-CATCH: an em dash becoming a colon, a full stop or a comma pair is not a change', () => {
  assert.strictEqual(H({ body: '<p>The euro sign: copy it below. It works on Discord.</p>' }), base);
  assert.strictEqual(H({ body: '<p>The euro sign. Copy it below. It works on Discord.</p>' }), base);
  assert.strictEqual(H({ body: '<p>The euro sign, copy it below, it works on Discord.</p>' }), base);
});
t('NON-CATCH: punctuation in the title, H1 and meta description is not a change', () => {
  assert.strictEqual(H({ title: 'Euro Sign (€) — Copy and Paste', h1: 'Euro Sign:', desc: 'The euro sign — ready to copy!' }), base);
});
t('NON-CATCH: an aria-label edit is not a change (the 2026-08-15 failure)', () => {
  const a = page(), b = page().replace('aria-label="Copy €"', 'aria-label="Copy the euro sign"');
  assert.notStrictEqual(a, b);
  assert.strictEqual(significanceHash(a), significanceHash(b));
});
t('NON-CATCH: on a real page, a link injected inside the footer block does not change the hash', () => {
  const real = fs.readFileSync(path.join(__dirname, '..', '..', 'index.html'), 'utf8');
  assert.ok(/<!--\s*BEGIN static footer/.test(real) && /<!--\s*END static footer/.test(real), 'index.html carries no static footer markers; the fixture format has drifted');
  const injected = real.replace(/(<!--\s*END static footer)/, '<a href="/answers/">Answers — every question</a>$1');
  assert.notStrictEqual(injected, real);
  assert.strictEqual(significanceHash(injected), significanceHash(real));
  assert.ok(stripStaticFooter(real).length < real.length);
});

// ── catches: what MUST advance lastmod ──────────────────────────────────────
t('a word changing in prose is a change', () => {
  assert.notStrictEqual(H({ body: '<p>The euro sign — copy it below. It works on Telegram.</p>' }), base);
});
t('a copy payload changing is a change, even by one symbol', () => {
  assert.notStrictEqual(H({ tile: '₤' }), base);
});
t('a symbol in visible text is content, not punctuation', () => {
  assert.notStrictEqual(H({ body: '<p>The euro sign ★ — copy it below. It works on Discord.</p>' }),
    H({ body: '<p>The euro sign ☆ — copy it below. It works on Discord.</p>' }));
});
t('an internal link added in the body (not the footer) is a change', () => {
  assert.notStrictEqual(H({ links: '<a href="/library/currency-symbols/">Currency</a><a href="/symbol/pound-sign/">Pound</a>' }), base);
});
t('title, H1 and description words are a change', () => {
  assert.notStrictEqual(H({ title: 'Euro Symbol (€): Copy and Paste' }), base);
  assert.notStrictEqual(H({ h1: 'Euro Symbol' }), base);
  assert.notStrictEqual(H({ desc: 'The euro symbol, ready to copy.' }), base);
});
t('normalizeText strips punctuation, folds case, and keeps symbols and digits', () => {
  assert.strictEqual(normalizeText('Unicode 18.0 — publishes: September 16, 2026 (€, ★)'), 'unicode 18 0 publishes september 16 2026 € ★');
});
t('NON-CATCH: a case-only change is not a change (the full-stop remedy capitalises the next word)', () => {
  assert.strictEqual(H({ body: '<p>The euro sign — copy it below. It works on discord.</p>' }), base);
});

// ── the date picker ─────────────────────────────────────────────────────────
t('pickSignificantDate returns the newest commit that changed the hash, not the newest touch', () => {
  const e = [{ hash: 'A', date: '2026-09-02' }, { hash: 'A', date: '2026-08-28' }, { hash: 'B', date: '2026-08-25' }];
  assert.strictEqual(pickSignificantDate(e), '2026-08-28');
});
t('pickSignificantDate: no differing pair means the oldest entry (page appeared, or walk capped)', () => {
  assert.strictEqual(pickSignificantDate([{ hash: 'A', date: '2026-09-02' }, { hash: 'A', date: '2026-08-20' }]), '2026-08-20');
  assert.strictEqual(pickSignificantDate([{ hash: 'A', date: '2026-09-02' }]), '2026-09-02');
  assert.strictEqual(pickSignificantDate([]), null);
});

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
