#!/usr/bin/env python3
"""Generate style.css's @font-face block from assets/fonts/manifest.json.

The rules are generated, never hand-written, for the same reason the library
hub directories are: the CSS and the files on disk cannot then disagree about
which weights and unicode-ranges exist. Adding a font means re-running this,
not editing style.css.

No flags: report what would change and exit 1 if stale (this is the gate).
--write: rewrite the block in place.

A manifest row carrying "stylesheet" is NOT put in style.css. It goes to that
file instead, generated whole, for a family only a few pages use and whose rules
are large: the Japanese worksheet face's unicode-ranges list thousands of kanji,
61 KB of CSS that every page on the site would otherwise download (measured
2026-10-04). Pages that need it link the stylesheet themselves.
"""
import argparse, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSS = os.path.join(ROOT, "style.css")
MANIFEST = os.path.join(ROOT, "assets", "fonts", "manifest.json")
BEGIN = "/* @self-hosted-fonts:begin -- generated by scripts/build-font-face-css.py; do not edit by hand */"
END = "/* @self-hosted-fonts:end */"


def block(manifest):
    order = sorted(
        manifest,
        key=lambda e: (e["family"], int(e["weight"]) if str(e["weight"]).isdigit() else 0, e["subset"]),
    )
    out = [BEGIN,
           "/* Served from this repo, not fonts.googleapis.com -- see assets/fonts/README.md",
           "   for why (Cloudflare Fonts drops a family missing from its own bundle). */"]
    for e in order:
        out.append("@font-face {")
        out.append("  font-family: '%s';" % e["family"])
        out.append("  font-style: %s;" % e["style"])
        out.append("  font-weight: %s;" % e["weight"])
        out.append("  font-display: swap;")
        out.append("  src: url('/assets/fonts/%s') format('woff2');" % e["file"])
        if e.get("unicodeRange"):
            out.append("  unicode-range: %s;" % e["unicodeRange"])
        out.append("}")
    out.append(END)
    return "\n".join(out)


def side_sheets(manifest, write):
    """Write/verify each separate stylesheet. Returns the number that are stale."""
    stale = 0
    for target in sorted({e["stylesheet"] for e in manifest if e.get("stylesheet")}):
        rows = [e for e in manifest if e.get("stylesheet") == target]
        body = block(rows).replace(BEGIN, "/* generated by scripts/build-font-face-css.py from assets/fonts/manifest.json; do not edit by hand */").replace(END, "") .rstrip() + "\n"
        path = os.path.join(ROOT, target)
        have = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if have == body:
            print("%s is current (%d rules)." % (target, len(rows)))
        elif write:
            open(path, "w", encoding="utf-8").write(body)
            print("%s written: %d @font-face rules." % (target, len(rows)))
        else:
            print("%s is STALE. Run: python3 scripts/build-font-face-css.py --write" % target)
            stale += 1
    return stale


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    manifest = json.load(open(MANIFEST, encoding="utf-8"))
    missing = [e["file"] for e in manifest
               if not os.path.exists(os.path.join(ROOT, "assets", "fonts", e["file"]))]
    if missing:
        print("ERROR: manifest names %d file(s) not on disk: %s" % (len(missing), ", ".join(missing[:5])))
        return 1

    if side_sheets(manifest, args.write):
        return 1
    manifest = [e for e in manifest if not e.get("stylesheet")]

    want = block(manifest)
    css = open(CSS, encoding="utf-8").read()
    if BEGIN in css:
        if END not in css:
            print("ERROR: style.css has the begin marker and no end marker.")
            return 1
        start = css.index(BEGIN)
        stop = css.index(END) + len(END)
        have = css[start:stop]
        new = css[:start] + want + css[stop:]
    else:
        have = ""
        new = want + "\n\n" + css

    if have == want:
        print("style.css @font-face block is current (%d rules, %d families)."
              % (len(manifest), len({e["family"] for e in manifest})))
        return 0

    if not args.write:
        print("style.css @font-face block is STALE. Run: python3 scripts/build-font-face-css.py --write")
        return 1

    open(CSS, "w", encoding="utf-8").write(new)
    print("style.css updated: %d @font-face rules across %d families."
          % (len(manifest), len({e["family"] for e in manifest})))
    return 0


if __name__ == "__main__":
    sys.exit(main())
