#!/usr/bin/env python3
"""
Turn each generator's internal *inventory* CSV into a Pinterest-importer-ready
`*_upload.csv` — the ONLY files you should upload to Pinterest's "Bulk create
Pins" tool.

Why a converter (and not just the generators):
  - The three pin generators (generate-pinterest.py, generate-collection-pins.py,
    generate-id-pins.py) write rich inventories with internal columns (boards,
    status, alt text, secondary boards, search volume). Those are useful to us
    but are NOT Pinterest's schema.
  - This step is decoupled from rendering, so it needs no Playwright/cairosvg and
    can refresh every upload CSV from the committed inventories in one command.
  - All schema/validation lives in scripts/pinterest_csv.py, so the upload format
    can never drift per-generator.

Media URL: built as <DOMAIN> + <inventory image path>. Since the R2 migration
(docs/pinterest-r2-migration.md), every generator writes the inventory's
image-path column as an R2 *object key* (e.g. "pinterest/base/<slug>.png"),
not a repo-relative disk path -- so DOMAIN now defaults to R2's public base
URL (R2_PUBLIC_BASE_URL, default "https://media.ultratextgen.com"), giving
"https://media.ultratextgen.com/pinterest/base/<slug>.png". Override with
PIN_MEDIA_DOMAIN for a one-off (e.g. pointing at a staging bucket):
  PIN_MEDIA_DOMAIN="https://staging-media.ultratextgen.com" \
    python3 scripts/build_pinterest_upload.py

A handful of pre-R2-migration inventory rows may still carry a legacy
"assets/pinterest/..." repo-relative path (anything not yet regenerated);
those resolve against DOMAIN the same way and will 404 until re-generated --
see scripts/migrate_pinterest_to_r2.py for the one-time backfill of
already-committed images.

Note: Pinterest's bulk CSV has a single "Pinterest board" column, so each pin is
filed to its PRIMARY board here. Secondary boards (in the inventory) are a manual
re-pin on Pinterest.

Run:  python3 scripts/build_pinterest_upload.py            # all sources
      python3 scripts/build_pinterest_upload.py id page    # a subset
"""
import csv
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")

_spec = importlib.util.spec_from_file_location(
    "pinterest_csv", os.path.join(HERE, "pinterest_csv.py"))
P = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(P)

DOMAIN = (os.environ.get("PIN_MEDIA_DOMAIN")
          or os.environ.get("R2_PUBLIC_BASE_URL", "https://media.ultratextgen.com"))

# Each source maps an inventory CSV's columns onto the normalized fields that
# pinterest_csv.upload_row() expects. `include` (optional) filters rows.
SOURCES = {
    "page": dict(
        inventory="pinterest_pins.csv",
        out="pinterest_pins_upload.csv",
        title="pin_title", image="pinterest_image_path",
        board="pinterest_board_primary", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords",
        include=lambda r: (r.get("include_in_pinterest") or "").strip().lower() == "yes"),
    "variants": dict(
        inventory="pinterest_pins_variants.csv",
        out="pinterest_pins_variants_upload.csv",
        title="pin_title", image="pinterest_image_path",
        board="pinterest_board_primary", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords",
        include=lambda r: (r.get("include_in_pinterest") or "").strip().lower() == "yes"),
    "collection": dict(
        inventory="collection_pins.csv",
        out="collection_pins_upload.csv",
        title="pin_title", image="pin_image_path",
        board="board_primary", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords"),
    "id": dict(
        inventory="id_pinterest_pins.csv",
        out="id_pinterest_pins_upload.csv",
        title="pin_title", image="image_path",
        board="board", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords"),
    "vertical_text": dict(
        inventory="vertical_text_pinterest_pins.csv",
        out="vertical_text_pinterest_pins_upload.csv",
        title="pin_title", image="image_path",
        board="board", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords"),
    # discord/roblox call BU.convert(...) directly from their own generator's
    # _build_upload() helper -- registered here so that call actually resolves
    # instead of raising KeyError (found while wiring the R2 migration: both
    # were missing from this table, so their upload CSVs were never actually
    # regenerated by a normal generator run).
    "discord": dict(
        inventory="discord_pinterest_pins.csv",
        out="discord_pinterest_pins_upload.csv",
        title="pin_title", image="image_path",
        board="board", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords"),
    "roblox": dict(
        inventory="roblox_pinterest_pins.csv",
        out="roblox_pinterest_pins_upload.csv",
        title="pin_title", image="image_path",
        board="board", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords"),
    "es": dict(
        inventory="es_pinterest_pins.csv",
        out="es_pinterest_pins_upload.csv",
        title="pin_title", image="image_path",
        board="board", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords"),
    # localized single-language boards (de, fr, it, nl, pl, pt, tr, vi) — same
    # inventory shape as "es", produced by scripts/generate-<locale>-pins.py
    # via scripts/_locale_pin_kit.py.
    **{loc: dict(
        inventory=f"{loc}_pinterest_pins.csv",
        out=f"{loc}_pinterest_pins_upload.csv",
        title="pin_title", image="image_path",
        board="board", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords")
       for loc in ("de", "fr", "it", "nl", "pl", "pt", "tr", "vi")},
    "gaming_names": dict(
        inventory="gaming_names_pinterest_pins.csv",
        out="gaming_names_pinterest_pins_upload.csv",
        title="pin_title", image="image_path",
        board="board", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords"),
    "nama_ff_keren": dict(
        inventory="nama_ff_keren_pinterest_pins.csv",
        out="nama_ff_keren_pinterest_pins_upload.csv",
        title="pin_title", image="image_path",
        board="board", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords"),
    # French topic boards (2026-07-20 expansion) — deep FR pages, not the /fr/
    # homepage, so each is its own board key rather than reusing "fr".
    **{loc: dict(
        inventory=f"{loc}_pinterest_pins.csv",
        out=f"{loc}_pinterest_pins_upload.csv",
        title="pin_title", image="image_path",
        board="board", description="pin_description",
        link="utm_destination_url", keywords="pin_keywords")
       for loc in ("fr_gaming", "fr_clavier", "fr_imprimables", "fr_tatouage",
                   "fr_esthetique", "fr_kaomoji", "fr_zodiaque",
                   "fr_style_reseau", "fr_outils")},
}


def convert(key, domain=DOMAIN):
    s = SOURCES[key]
    inv = os.path.join(DATA, s["inventory"])
    if not os.path.exists(inv):
        print(f"  [{key}] skip — no inventory at data/{s['inventory']}")
        return None
    include = s.get("include", lambda r: True)
    rows = []
    with open(inv, encoding="utf-8-sig") as f:
        for r in csv.DictReader(f):
            if not include(r):
                continue
            img = (r.get(s["image"]) or "").strip()
            if not img:
                continue
            rows.append(P.upload_row(
                r.get(s["title"], ""),
                P.public_media_url(domain, img),
                r.get(s["board"], ""),
                description=r.get(s["description"], ""),
                link=r.get(s["link"]) or r.get("destination_url", ""),
                keywords=r.get(s["keywords"], "")))
    out = os.path.join(DATA, s["out"])
    P.write_upload_csv(out, rows)
    print(f"  [{key}] {len(rows):3} pins  data/{s['inventory']} -> data/{s['out']}")
    return out


def main():
    keys = [a for a in sys.argv[1:] if not a.startswith("-")] or list(SOURCES)
    bad = [k for k in keys if k not in SOURCES]
    if bad:
        sys.exit(f"unknown source(s): {', '.join(bad)} (choose from {list(SOURCES)})")
    print(f"building Pinterest upload CSVs (media domain: {DOMAIN})")
    for k in keys:
        convert(k)


if __name__ == "__main__":
    main()
