#!/usr/bin/env python3
"""Build the Japanese worksheet face (Klee One SemiBold) as unicode-range chunks.

Japanese worksheets need a textbook-style face (教科書体 style: とめ・はね・はらい
drawn as a pencil writes them), not a gothic UI face. Klee One (Fontworks, OFL-1.1)
is the openly licensed face of that kind, and it covers 8,114 kanji including the
name variants 髙 (U+9AD9) and 﨑 (U+FA11).

The whole font is 8.9 MB as TTF, so it is never shipped whole. Google Fonts slices it
into 124 frequency chunks per weight; this script slices it by WHAT A WORKSHEET ASKS
FOR instead, so a kana sheet downloads one small file and a grade-1 kanji sheet one
more:

  ja-kana    Latin, punctuation, kana, half/full-width forms  (every JA sheet)
  ja-g1..g6  the kanji of each school grade (学年別漢字配当表, 2020)
  ja-joyo    the rest of the 2,136 常用漢字
  ja-jinmei  人名用漢字 (names may legally use only joyo + jinmeiyo)
  ja-ext-N   every other kanji the face carries, in codepoint blocks

Each chunk is a woff2 with its own unicode-range, written to assets/fonts/ with a
manifest row, so scripts/build-font-face-css.py emits the @font-face rules into
assets/fonts/ja-print.css (never style.css: the kanji ranges are 61 KB of CSS) and the
browser fetches only the chunks a sheet's characters fall in.

Build-time only: needs `pip install fonttools brotli`. The kanji lists live in
scripts/lib/ja_print_kanji.json (grades from the MEXT table, joyo/jinmeiyo from Unicode's
Unihan kJoyoKanji / kJinmeiyoKanji fields), which this script reads.

  python3 scripts/build-ja-print-fonts.py --ttf KleeOne-SemiBold.ttf
  python3 scripts/build-font-face-css.py --write
"""
import argparse, hashlib, io, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTDIR = os.path.join(ROOT, "assets", "fonts")
MANIFEST = os.path.join(FONTDIR, "manifest.json")
KANJI = os.path.join(ROOT, "scripts", "lib", "ja_print_kanji.json")
FAMILY = "Klee One"
WEIGHT = "600"
SOURCE = "https://github.com/google/fonts/raw/main/ofl/kleeone/KleeOne-SemiBold.ttf"

# Everything a kana, romaji or name sheet can contain apart from kanji.
KANA_RANGES = [
    (0x0020, 0x007E), (0x00A0, 0x00FF), (0x0100, 0x017F),  # Latin incl. macron vowels
    (0x2010, 0x2027), (0x2030, 0x203B),                     # dashes, quotes, ellipsis, ※
    (0x2190, 0x2193), (0x25A0, 0x25CF), (0x2605, 0x2606),   # arrows, shapes, stars
    (0x3000, 0x303F),                                       # CJK punctuation 、。「」々〆
    (0x3041, 0x309F), (0x30A0, 0x30FF), (0x31F0, 0x31FF),   # hiragana, katakana, small ext
    (0xFF01, 0xFF9F), (0xFFE0, 0xFFE6),                     # full-width, half-width kana
]


def ranges_to_css(cps):
    cps = sorted(set(cps))
    out, start, prev = [], None, None
    for c in cps:
        if start is None:
            start = prev = c
        elif c == prev + 1:
            prev = c
        else:
            out.append((start, prev)); start = prev = c
    if start is not None:
        out.append((start, prev))
    return ", ".join("U+%X" % a if a == b else "U+%X-%X" % (a, b) for a, b in out)


def subset(ttf_path, cps):
    from fontTools import subset as fts
    from fontTools.ttLib import TTFont
    opts = fts.Options()
    opts.flavor = "woff2"
    opts.layout_features = ["vert", "vrt2", "ccmp", "kern", "palt", "hwid", "fwid"]
    opts.name_IDs = ["*"]           # keep the copyright/licence name records
    opts.notdef_outline = True
    opts.hinting = False
    font = TTFont(ttf_path)
    sub = fts.Subsetter(opts)
    sub.populate(unicodes=cps)
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    return buf.getvalue()


GRADES_JS = os.path.join(ROOT, "js", "printables", "jaKanjiGrades.js")


def write_grades(lists, check=False):
    """js/printables/jaKanjiGrades.js: the grade presets of the kanji sheet.
    Generated from the same list the font chunks are cut from, so a preset can
    never name a kanji the grade chunk does not carry."""
    body = ("/* GENERATED by scripts/build-ja-print-fonts.py from scripts/lib/ja_print_kanji.json;"
            " do not edit by hand.\n   学年別漢字配当表 (MEXT, in force 2020-04-01): 80/160/200/202/193/191 = 1026. */\n"
            "(function () {\n  \"use strict\";\n  window.UTG_JA_KANJI_GRADES = " +
            json.dumps(lists["grades"], ensure_ascii=False, sort_keys=True) + ";\n})();\n")
    have = open(GRADES_JS, encoding="utf-8").read() if os.path.exists(GRADES_JS) else None
    if check:
        return have == body
    open(GRADES_JS, "w", encoding="utf-8").write(body)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", help="path to KleeOne-SemiBold.ttf from google/fonts")
    ap.add_argument("--grades-only", action="store_true", help="only (re)write js/printables/jaKanjiGrades.js")
    ap.add_argument("--check", action="store_true", help="exit 1 if jaKanjiGrades.js is stale")
    ap.add_argument("--ext-chunk", type=int, default=900, help="kanji per ja-ext chunk")
    args = ap.parse_args()

    lists = json.load(open(KANJI, encoding="utf-8"))
    counts = [len(lists["grades"][g]) for g in "123456"]
    if counts != [80, 160, 200, 202, 193, 191]:
        raise SystemExit("grade lists do not match the MEXT table counts: %s" % counts)
    if args.check:
        ok = write_grades(lists, check=True)
        print("jaKanjiGrades.js is %s" % ("current" if ok else "STALE: run --grades-only"))
        return 0 if ok else 1
    write_grades(lists)
    if args.grades_only:
        print("wrote js/printables/jaKanjiGrades.js")
        return 0
    if not args.ttf:
        ap.error("--ttf is required unless --grades-only or --check is passed")

    from fontTools.ttLib import TTFont
    cmap = TTFont(args.ttf).getBestCmap()
    have = set(cmap)

    chunks = []
    kana = [c for a, b in KANA_RANGES for c in range(a, b + 1) if c in have]
    chunks.append(("ja-kana", kana))
    used = set()
    for g in "123456":
        cps = [ord(ch) for ch in lists["grades"][g]]
        missing = [chr(c) for c in cps if c not in have]
        if missing:
            raise SystemExit("grade %s kanji missing from the face: %s" % (g, "".join(missing)))
        chunks.append(("ja-g" + g, cps)); used.update(cps)
    joyo = [ord(ch) for ch in lists["joyo"] if ord(ch) not in used and ord(ch) in have]
    chunks.append(("ja-joyo", joyo)); used.update(joyo)
    jin = [ord(ch) for ch in lists["jinmeiyo"] if ord(ch) not in used and ord(ch) in have]
    chunks.append(("ja-jinmei", jin)); used.update(jin)
    rest = sorted(c for c in have if c not in used and c not in set(kana)
                  and (0x3400 <= c <= 0x9FFF or 0xF900 <= c <= 0xFAFF or 0x20000 <= c <= 0x3FFFF))
    for i in range(0, len(rest), args.ext_chunk):
        chunks.append(("ja-ext-%d" % (i // args.ext_chunk + 1), rest[i:i + args.ext_chunk]))

    manifest = json.load(open(MANIFEST, encoding="utf-8"))
    manifest = [e for e in manifest if e["family"] != FAMILY]
    total = 0
    for name, cps in chunks:
        data = subset(args.ttf, cps)
        fn = "klee-one-%s-%s.woff2" % (name, WEIGHT)
        open(os.path.join(FONTDIR, fn), "wb").write(data)
        total += len(data)
        manifest.append({"family": FAMILY, "file": fn, "weight": WEIGHT, "style": "normal",
                         "unicodeRange": ranges_to_css(cps), "subset": name, "bytes": len(data),
                         "sha256": hashlib.sha256(data).hexdigest(), "source": SOURCE,
                         "stylesheet": "assets/fonts/ja-print.css",
                         "chars": len(cps)})
        print("%-12s %5d chars %8.1f KB" % (name, len(cps), len(data) / 1024))
    manifest.sort(key=lambda e: (e["family"], int(e["weight"]) if str(e["weight"]).isdigit() else 0, e["subset"]))
    json.dump(manifest, open(MANIFEST, "w", encoding="utf-8"), indent=1)
    print("%s %s: %d chunk(s), %.1f KB total. Now run scripts/build-font-face-css.py --write"
          % (FAMILY, WEIGHT, len(chunks), total / 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
