#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""sync_events_hub.py — rebuild the /events/ hub card grid from the specs.

The hub listed its events in frozen build order, so Chinese New Year led the
page all through August — the least useful card for the next six months — and
every card was text-only and visually identical. It was also hand-maintained,
so a new event page could ship without ever appearing on its own hub.

This regenerates the grid between the HUB-CARDS markers, ordered by whichever
event comes next, with a date chip and one emoji per card. Deterministic dates
are baked in; lunar events (Eid, Chinese New Year) carry their rule instead and
are filled in and re-sorted at runtime by js/events/eventDates.js, for the same
reason as the per-page date line — ICU in the browser is the only source for
those dates this repo can honestly use.

Usage
-----
    python3 scripts/sync_events_hub.py            # report only
    python3 scripts/sync_events_hub.py --write    # apply
"""

import argparse
import html
import json
import pathlib
import re
import sys

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO = SCRIPT_DIR.parent
SPEC_DIR = REPO / "data" / "event_page_specs"
HUB = REPO / "events" / "index.html"

sys.path.insert(0, str(SCRIPT_DIR / "lib"))
from event_occurrence import format_date, is_lunar, next_occurrences  # noqa: E402

START = "<!-- HUB-CARDS:START (generated by scripts/sync_events_hub.py — do not hand-edit) -->"
END = "<!-- HUB-CARDS:END -->"

# One emoji per event. Kept here rather than in the specs because it is a
# property of this grid's presentation, not of the event page itself.
EMOJI = {
    "chinese-new-year": "🧧", "christmas": "🎄", "diwali": "🪔", "easter": "🐰",
    "eid-mubarak": "🌙", "fathers-day": "👔", "halloween": "🎃",
    "mothers-day": "💐", "new-year": "🎆", "thanksgiving": "🦃",
    "valentines-day": "💘", "ramadan": "🌙", "st-patricks-day": "🍀",
    "july-4th": "🎇", "graduation": "🎓",
}

esc = html.escape


def load_cards():
    cards = []
    for path in sorted(SPEC_DIR.glob("*.json")):
        if path.name.startswith("_"):
            continue
        spec = json.loads(path.read_text(encoding="utf-8"))
        if spec.get("language", "en") != "en":
            continue  # the EN hub lists EN pages only
        slug = spec["slug"]
        occurrence = spec.get("occurrence")
        dates = next_occurrences(occurrence) if occurrence else []
        cards.append({
            "slug": slug,
            "name": spec["event_name"],
            "desc": spec.get("hub_card_desc") or spec["hero_tagline"],
            "emoji": EMOJI.get(slug, "📅"),
            "dates": [d.isoformat() for d in dates],
            "chip": format_date(dates[0], "en", with_weekday=False) if dates else "",
            "occurrence": occurrence if is_lunar(occurrence) else None,
            # Undated events sort last server-side; the runtime pass fixes the
            # lunar ones once it can resolve them.
            "sort": dates[0].isoformat() if dates else "9999-12-31",
        })
    cards.sort(key=lambda c: (c["sort"], c["name"]))
    return cards


def render(cards):
    out = [START]
    for c in cards:
        attrs = ""
        if c["dates"]:
            attrs = f' data-event-dates="{esc(json.dumps(c["dates"]), quote=True)}"'
        elif c["occurrence"]:
            attrs = f' data-occurrence="{esc(json.dumps(c["occurrence"]), quote=True)}"'
        out.append(
            f'    <a href="/events/{c["slug"]}/" class="compare-card variant-muted '
            f'u-no-underline event-hub-card"{attrs}>\n'
            f'      <span class="event-hub-emoji" aria-hidden="true">{c["emoji"]}</span>\n'
            f'      <h4>{esc(c["name"])}</h4>\n'
            f'      <p class="event-hub-when" data-event-chip>{esc(c["chip"])}</p>\n'
            f'      <p>{esc(c["desc"])}</p>\n'
            "    </a>"
        )
    out.append("    " + END)
    return "\n".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="apply changes")
    args = parser.parse_args(argv)

    cards = load_cards()
    block = render(cards)
    text = HUB.read_text(encoding="utf-8")

    if START in text and END in text:
        pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
        new_text = pattern.sub(lambda _: block.strip(), text, count=1)
    else:
        # First run: replace the existing hand-written run of event cards.
        first = text.find('<a href="/events/')
        if first == -1:
            print("[ERROR] no event cards found in the hub, and no markers to replace")
            return 1
        last_close = text.rfind("</a>", first)
        if last_close == -1:
            print("[ERROR] could not find the end of the card grid")
            return 1
        line_start = text.rfind("\n", 0, first) + 1
        new_text = text[:line_start] + block.strip() + "\n" + text[last_close + 4:].lstrip("\n")

    print(f"{len(cards)} card(s), next up: " + ", ".join(
        f'{c["name"]} ({c["chip"] or "lunar — resolved in browser"})' for c in cards[:4]
    ))
    if new_text == text:
        print("Hub already up to date.")
        return 0
    if not args.write:
        print("Would rewrite events/index.html — run with --write to apply.")
        return 0
    HUB.write_text(new_text, encoding="utf-8")
    print("Wrote events/index.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
