#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Weekly PR digest generator.

Reads a JSON array of merged pull requests (as produced by
`gh pr list --json number,title,url,mergedAt,labels,files`) on **stdin** and
writes a markdown digest that classifies each PR into an infrastructure
**lane** by its changed file paths. The digest is the deterministic input the
weekly infrastructure review consumes (see docs/README.md →
"Weekly infrastructure review").

Reading PRs from stdin (rather than calling the API directly) keeps this script
network-free and unit-testable with a fixture.

Usage:
    gh pr list --base main --state merged \
        --search "merged:>=2026-06-10" \
        --json number,title,url,mergedAt,labels,files --limit 200 \
      | python3 scripts/weekly_pr_digest.py --since 2026-06-10 --until 2026-06-17 \
      > docs/infra-review/2026-06-17.md
"""

import argparse
import datetime as dt
import json
import sys

# Path-prefix → lane. Ordered: the FIRST matching rule wins, so put the more
# specific prefixes before generic ones. Lanes mirror docs/README.md.
LANE_RULES = [
    ("library/", "Library pages"),
    ("category/", "Category pages"),
    ("answers/", "Answer pages"),
    ("usecase/", "Usecase pages"),
    ("guide/", "Guide pages"),
    ("discord/", "Platform pages"),
    ("facebook/", "Platform pages"),
    ("instagram/", "Platform pages"),
    ("linkedin/", "Platform pages"),
    ("pinterest/", "Platform pages"),
    ("snapchat/", "Platform pages"),
    ("telegram/", "Platform pages"),
    ("tiktok/", "Platform pages"),
    ("whatsapp/", "Platform pages"),
    ("x/", "Platform pages"),
    ("youtube/", "Platform pages"),
    ("assets/", "Image SEO"),
    ("data/library_opportunities", "Opportunity backlog"),
    ("data/", "Data / backlog"),
    (".github/workflows/", "CI / automation"),
    ("scripts/", "Scripts / tooling"),
    ("docs/", "Docs"),
    ("CLAUDE.md", "Docs"),
    ("style.css", "Styling"),
    ("symbol-explorer", "Symbol explorer"),
    ("renderer.js", "Core JS"),
    ("styles.js", "Core JS"),
    ("script.js", "Core JS"),
    ("header.js", "Core JS"),
    ("fonts.json", "Core JS"),
    ("js/", "Core JS"),
    ("package.json", "Scripts / tooling"),
    ("sitemap.xml", "SEO / sitemap"),
    ("robots.txt", "SEO / sitemap"),
    ("_redirects", "Routing"),
    ("locales/", "i18n"),
    ("es/", "i18n"),
    ("de/", "i18n"),
    ("fr/", "i18n"),
    ("id/", "i18n"),
    ("it/", "i18n"),
    ("nl/", "i18n"),
    ("pl/", "i18n"),
    ("pt/", "i18n"),
    ("tl/", "i18n"),
    ("tr/", "i18n"),
    ("vi/", "i18n"),
]

# A lane label used when no rule matched any of a PR's files. These are the
# signal the review is looking for: work that doesn't fit a known lane.
UNCLASSIFIED = "Unclassified — possible new lane (signal!)"


def classify_paths(paths):
    """Return the set of lanes a list of file paths touches."""
    lanes = set()
    for p in paths:
        matched = None
        for prefix, lane in LANE_RULES:
            if p.startswith(prefix) or ("/" not in prefix and p == prefix):
                matched = lane
                break
        lanes.add(matched if matched else UNCLASSIFIED)
    # If a PR touched real lanes *and* something unclassified, keep both — the
    # unclassified part is still a signal worth surfacing.
    return lanes


def pr_files(pr):
    """Extract changed file paths from a gh PR json object (tolerant of shape)."""
    files = pr.get("files") or []
    out = []
    for f in files:
        if isinstance(f, str):
            out.append(f)
        elif isinstance(f, dict):
            path = f.get("path") or f.get("filename")
            if path:
                out.append(path)
    return out


def build_digest(prs, since, until):
    lines = []
    lines.append(f"# Weekly PR digest — {since} → {until}")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/weekly_pr_digest.py` "
        "(workflow: `.github/workflows/weekly-pr-digest.yml`). "
        "Input for the [weekly infrastructure review](../README.md#weekly-infrastructure-review)."
    )
    lines.append("")

    if not prs:
        lines.append("_No PRs merged to `main` in this window._")
        lines.append("")
        return "\n".join(lines)

    # Group PRs by lane.
    by_lane = {}
    for pr in prs:
        lanes = classify_paths(pr_files(pr)) or {UNCLASSIFIED}
        for lane in lanes:
            by_lane.setdefault(lane, []).append(pr)

    # Summary table (lanes by PR count), unclassified last but highlighted.
    lines.append("## Lanes touched this week")
    lines.append("")
    lines.append("| Lane | PRs |")
    lines.append("|---|---|")
    ordered = sorted(
        by_lane.items(),
        key=lambda kv: (kv[0] == UNCLASSIFIED, -len(kv[1]), kv[0]),
    )
    for lane, items in ordered:
        lines.append(f"| {lane} | {len(items)} |")
    lines.append("")

    if UNCLASSIFIED in by_lane:
        lines.append(
            f"> ⚠️ **{len(by_lane[UNCLASSIFIED])} PR(s) didn't map to a known "
            "lane.** Review these first — they may signal an emerging lane that "
            "belongs in `docs/README.md`."
        )
        lines.append("")

    # Per-PR detail.
    lines.append("## Merged PRs")
    lines.append("")
    for pr in sorted(prs, key=lambda p: p.get("number", 0)):
        num = pr.get("number", "?")
        title = pr.get("title", "(no title)")
        url = pr.get("url", "")
        lanes = sorted(classify_paths(pr_files(pr)) or {UNCLASSIFIED})
        files = pr_files(pr)
        head = f"- **#{num}** [{title}]({url})" if url else f"- **#{num}** {title}"
        lines.append(head)
        lines.append(f"  - Lanes: {', '.join(lanes)}")
        lines.append(f"  - Files: {len(files)} changed")
        lines.append("")

    lines.append("## Review checklist")
    lines.append("")
    lines.append(
        "1. For each **Unclassified** PR: is this a new lane, or a path the "
        "classifier should learn? Update `docs/README.md` and/or `LANE_RULES`."
    )
    lines.append(
        "2. Did any PR close a gap in `docs/README.md` → Known gaps? Tick it off."
    )
    lines.append(
        "3. Any manual work recurring 3+ weeks? Flag it to systematize."
    )
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    today = dt.date.today()
    ap.add_argument("--since", default=str(today - dt.timedelta(days=7)))
    ap.add_argument("--until", default=str(today))
    args = ap.parse_args(argv)

    raw = sys.stdin.read().strip()
    prs = json.loads(raw) if raw else []
    if not isinstance(prs, list):
        sys.stderr.write("[error] expected a JSON array of PRs on stdin\n")
        return 1

    sys.stdout.write(build_digest(prs, args.since, args.until))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
